// Sample JSON practice, for reference 

var columnsConfig = {
    "so_num": { "format": "text" },
    "so_date_issued": { "format": "date" },
    "customer_name": { "format": "text" },
    "line_type": { "format": "text" },
    "line_number": { "format": "text" },
    "product_num": { "format": "text" },
    "product_description": { "format": "text" },
    "shipped_qty": { "format": "number" },
    "total_revenue": { "format": "currency" },
    "line_unit_cost": { "format": "currency" },
    "total_cogs": { "format": "currency" }
};


// Predefined column configurations for different SQL queries

var columnsConfig = {
    "so_num": { "format": "text" },
    "so_datecreated": { "format": "date" },
    "so_dateissued": { "format": "date" },
    "so_datecompleted": { "format": "date" },
    "so_statusname": { "format": "text" },
    "post_date": { "format": "date" },
    "customer_name": { "format": "text" },
    "customer_po": { "format": "text" },
    "bill_name": { "format": "text" },
    "bill_adr": { "format": "text" },
    "bill_city": { "format": "text" },
    "bill_state": { "format": "text" },
    "bill_zip": { "format": "text" },
    "bill_country": { "format": "text" },
    "ship_name": { "format": "text" },
    "ship_adr": { "format": "text" },
    "ship_city": { "format": "text" },
    "ship_state": { "format": "text" },
    "ship_zip": { "format": "text" },
    "ship_country": { "format": "text" },
    "line_type": { "format": "text" },
    "line_number": { "format": "text" },
    "product_num": { "format": "text" },
    "product_description": { "format": "text" },
    "shipped_qty": { "format": "number" },
    "total_revenue": { "format": "currency" },
    "line_unit_price": { "format": "currency" },
    "total_cogs": { "format": "currency" },
    "po_num": { "format": "text" },
    "po_dateissued": { "format": "date" },
    "receive_lgp": { "format": "text" },
    "vendor_name": { "format": "text" },
    "date_posted": { "format": "date" },
    "date_received": { "format": "date" },
    "date_reconciled": { "format": "date" },
    "line_part_num": { "format": "text" },
    "line_part_description": { "format": "text" },
    "vendor_part_num": { "format": "text" },
    "line_unit_cost": { "format": "currency" },
    "line_qty_received": { "format": "number" },
    "line_posted_total_cost": { "format": "currency" },
    "uom_code": { "format": "text" },
    "po_status": { "format": "text" },
    "po_delivery_date": { "format": "date" },
    "po_email": { "format": "text" },
    "po_phone": { "format": "text" },
    "poitem_status": { "format": "text" },
    "part_number": { "format": "text" },
    "part_desc": { "format": "text" },
    "vendor_part_num": { "format": "text" },
    "line_delivery_date": { "format": "date" },
    "qty_ordered": { "format": "number" },
    "qty_received": { "format": "number" },
    "qty_balance": { "format": "number" },
    "so_shipto_city": { "format": "text" },
    "so_shipto_state": { "format": "text" },
    "so_shipto_country": { "format": "text" },
    "soitem_type": { "format": "text" },
    "line_sequence": { "format": "text" },
    "line_product_num": { "format": "text" },
    "line_product_desc": { "format": "text" },
    "line_order_qty": { "format": "number" },
    "line_picked_qty": { "format": "number" },
    "line_fulfilled_qty": { "format": "number" },
    "line_open_qty": { "format": "number" },
    "uom_code": { "format": "text" },
    "line_status": { "format": "text" }
};

